http_server:
  address: ":8081"
  timeout: "2s"
jwt:
  issuer: auth-service
  expires_in: 12h
  public_key: /app/jwtRS256.key.pub   # Путь внутри контейнера
  private_key: /app/jwtRS256.key      # Путь внутри контейнера